#!/bin/bash

# build name
if [ ! "$#" -eq "1" ]; then NAME="gafe6";
else NAME="$1";
fi

# conditions for build envirnment (osc vs local)
case "$USER" in
	mike) 	 CCFLAGS="-ccbin /usr/bin/g++-4.9" ;;
	ksu0236) CCFLAGS=" " ;;
	*)	 CCFLAGS=" " ;;
esac

TARGETS="extlib/gmsh_io/gmsh_io.cpp genrand.cpp main.cu";
FLAGS="-lcurand -Wno-deprecated-gpu-targets";

time nvcc $TARGETS $FLAGS -o "$NAME";
#time nvcc $CCFLAGS extlib/gmsh_io/gmsh_io.cpp genrand.cpp main.cu -lcurand -o "$NAME";
#time nvcc -ccbin /usr/bin/g++-4.9 extlib/gmsh_io/gmsh_io.cpp genrand.cpp gpuinfo.cu -lcurand -o "$NAME";
